"""CLI: measure the corpus and write the dataset report.

Produces docs/dataset-report.md, the figures it references, and the raw
statistics as JSON so the numbers in the write-up are reproducible rather than
transcribed by hand.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .analysis import BERT_TOKEN_LIMIT, LONGFORMER_TOKEN_LIMIT, build_report
from .cuad import load_documents
from .labels import LABEL_NAMES
from .splits import load_splits


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--documents", type=Path, default=Path("data/processed/documents.jsonl"))
    parser.add_argument("--splits", type=Path, default=Path("data/processed/splits.json"))
    parser.add_argument("--out_md", type=Path, default=Path("docs/dataset-report.md"))
    parser.add_argument("--out_json", type=Path, default=Path("docs/dataset-stats.json"))
    parser.add_argument("--figures_dir", type=Path, default=Path("docs/figures"))
    parser.add_argument("--window", type=int, default=300)
    parser.add_argument("--overlap", type=int, default=100)
    parser.add_argument("--no_figures", action="store_true")
    return parser.parse_args()


def _row(values: list) -> str:
    return "| " + " | ".join(str(v) for v in values) + " |"


def render_markdown(report: dict, figures: list[Path], md_path: Path) -> str:
    lengths = report["document_lengths"]
    chunks = report["chunk_labels"]
    doc_labels = report["document_labels"]
    spans = report["span_lengths"]

    def figure(name: str, alt: str) -> str:
        match = [f for f in figures if f.name == name]
        if not match:
            return ""
        rel = Path(*match[0].parts[len(md_path.parent.parts) :])
        return f"\n![{alt}]({rel.as_posix()})\n"

    over_bert = lengths["exceeding_bert_512"]
    over_long = lengths["exceeding_longformer_4096"]
    total_docs = lengths["documents"]

    lines = [
        "# Dataset report — CUAD v1, six risk clause categories",
        "",
        "Generated by `legal-risk-analyze`. Every number here is reproduced from",
        "`dataset-stats.json`; nothing is transcribed by hand.",
        "",
        "## 1. Document length forces the architecture",
        "",
        _row(["Statistic", "Words", "Estimated tokens"]),
        _row(["---", "---:", "---:"]),
    ]
    for key in ("min", "p25", "median", "mean", "p75", "p95", "max"):
        lines.append(
            _row([key, f"{lengths['words'][key]:,.0f}", f"{lengths['estimated_tokens'][key]:,.0f}"])
        )

    lines += [
        "",
        f"**{over_bert} of {total_docs} contracts ({over_bert / total_docs:.1%}) exceed BERT's "
        f"{BERT_TOKEN_LIMIT}-token window.** "
        f"{over_long} ({over_long / total_docs:.1%}) exceed Longformer's {LONGFORMER_TOKEN_LIMIT}.",
        "",
        "Truncating at 512 tokens is not a small loss of context here: it discards most",
        "of nearly every contract. Since the clauses we want sit anywhere in the document,",
        "and insurance or liability terms usually sit late, truncation removes precisely",
        "the text the task depends on.",
        "",
        f"The second figure matters more for the architecture: **{over_long / total_docs:.0%} of contracts",
        f"exceed Longformer's {LONGFORMER_TOKEN_LIMIT}-token window as well.** Long context alone does",
        "not solve the problem, so chunking is not a fallback for the leftovers — it is required",
        "for either model. What Longformer changes is how much context each chunk can hold, which",
        "is the thing the Problem 2 experiment actually measures.",
        figure("document_lengths.png", "Distribution of contract lengths against the 512-token limit"),
        "## 2. The real class imbalance",
        "",
        f"At a {chunks['window']}-word window with {chunks['overlap']}-word overlap, the corpus",
        f"yields **{chunks['chunks']:,} chunks**, of which **{chunks['unlabelled_rate']:.1%} carry",
        "no label at all**.",
        "",
        _row(["Label", "Documents", "Spans", "Positive chunks", "Rate", "pos_weight"]),
        _row(["---", "---:", "---:", "---:", "---:", "---:"]),
    ]
    for name in LABEL_NAMES:
        per = chunks["per_label"][name]
        lines.append(
            _row(
                [
                    name,
                    doc_labels[name]["documents"],
                    doc_labels[name]["spans"],
                    f"{per['positive_chunks']:,}",
                    f"{per['positive_rate']:.2%}",
                    f"{per['pos_weight']:.0f}×",
                ]
            )
        )

    lines += [
        "",
        "**This corrects a claim in the project brief.** The brief describes the classes as",
        "\"reasonably balanced (12–20% each)\", which is true only of clause occurrences counted",
        "among themselves. A classifier does not see clauses among themselves; it sees every",
        "chunk of every contract, and against that denominator the positive rate for each label",
        f"is between {min(chunks['per_label'][n]['positive_rate'] for n in LABEL_NAMES):.1%} and "
        f"{max(chunks['per_label'][n]['positive_rate'] for n in LABEL_NAMES):.1%}.",
        "",
        "Three consequences follow:",
        "",
        "1. **Accuracy is meaningless.** A model predicting all-negative scores above 95% on",
        "   every label. Precision, recall and F1 per class are the only honest metrics.",
        "2. **Unweighted BCE will collapse to the negative class.** The `pos_weight` column",
        "   gives the balancing factor per label for a weighted loss.",
        "3. **A 0.5 decision threshold is arbitrary.** Thresholds should be tuned per label on",
        "   the validation split, and PR-AUC reported alongside F1 since it is threshold-free.",
        figure("chunk_positive_rates.png", "Positive chunk rate per label"),
        "## 3. Clause length against the chunk window",
        "",
        _row(["Label", "Spans", "Median words", "p95 words", "Longest"]),
        _row(["---", "---:", "---:", "---:", "---:"]),
    ]
    for name in LABEL_NAMES:
        s = spans[name]
        if not s.get("spans"):
            continue
        lines.append(
            _row([name, s["spans"], f"{s['median']:.0f}", f"{s['p95']:.0f}", f"{s['max']:.0f}"])
        )

    worst = max((spans[n].get("p95", 0) for n in LABEL_NAMES), default=0)
    lines += [
        "",
        f"The longest 5% of clauses reach about {worst:.0f} words, against a {chunks['window']}-word",
        f"window. The {chunks['overlap']}-word overlap exists so a clause landing on a boundary",
        "still appears whole in a neighbouring window, which the pipeline tests verify directly.",
        "",
        "## 4. Labels co-occur, so this is multi-label",
        "",
        "Contracts carrying more than one of the six labels:",
        "",
        _row(["Distinct labels in a contract", "Contracts"]),
        _row(["---:", "---:"]),
    ]
    for count, n_docs in report["labels_per_document"].items():
        lines.append(_row([count, n_docs]))

    multi = sum(v for k, v in report["labels_per_document"].items() if k > 1)
    lines += [
        "",
        f"{multi} of {total_docs} contracts carry two or more labels, which rules out a softmax",
        "over mutually exclusive classes. Six independent sigmoid outputs with binary",
        "cross-entropy is the correct head.",
        figure("label_cooccurrence.png", "Label co-occurrence across contracts"),
    ]

    if "split_balance" in report:
        lines += [
            "## 5. The splits are representative",
            "",
            "Splits are assigned per document, never per chunk: overlapping windows of one",
            "contract would otherwise land on both sides of the split and near-duplicate text",
            "would be scored as held out.",
            "",
            _row(["Split", "Documents"] + list(LABEL_NAMES)),
            _row(["---", "---:"] + ["---:"] * len(LABEL_NAMES)),
        ]
        for split, data in report["split_balance"].items():
            lines.append(
                _row(
                    [split, data["documents"]]
                    + [f"{data['label_rates'][n]:.0%}" for n in LABEL_NAMES]
                )
            )
        lines.append(figure("split_balance.png", "Per-label document rate by split"))

    lines += [
        "## 6. Challenges, and what each one forces",
        "",
        _row(["Challenge", "Evidence", "Consequence for the model"]),
        _row(["---", "---", "---"]),
        _row(
            [
                "Documents vastly exceed the context window",
                f"{over_bert / total_docs:.0%} over 512 tokens, longest {lengths['words']['max']:,.0f} words",
                "Chunking is mandatory; long-context models are worth comparing",
            ]
        ),
        _row(
            [
                "Severe negative-class dominance",
                f"{chunks['unlabelled_rate']:.0%} of chunks unlabelled",
                "Weighted loss, tuned thresholds, per-class metrics",
            ]
        ),
        _row(
            [
                "Sparse positives per label",
                f"as few as {min(chunks['per_label'][n]['positive_chunks'] for n in LABEL_NAMES):,} positive chunks",
                "High variance between runs; report seeds and per-class support",
            ]
        ),
        _row(
            [
                "Labels co-occur",
                f"{multi} contracts carry 2+ labels",
                "Sigmoid + BCE, not softmax",
            ]
        ),
        _row(
            [
                "Annotation is span-level, supervision is chunk-level",
                "3,000+ spans mapped onto chunks by overlap",
                "The overlap rule is a modelling choice, exposed as `min_overlap_ratio`",
            ]
        ),
        _row(
            [
                "Legal English is domain-specific and OCR-noisy",
                "irregular whitespace and page furniture throughout the corpus",
                "Motivates the Legal-BERT vs BERT comparison",
            ]
        ),
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    documents = load_documents(args.documents)
    assignment = load_splits(args.splits) if args.splits.exists() else None
    report = build_report(documents, assignment, window=args.window, overlap=args.overlap)

    figures: list[Path] = []
    if not args.no_figures:
        from .figures import render_all

        figures = render_all(report, args.figures_dir)

    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(render_markdown(report, figures, args.out_md), encoding="utf-8")

    serialisable = json.loads(json.dumps(report, default=list))
    serialisable["document_lengths"].pop("_raw_words", None)
    args.out_json.write_text(json.dumps(serialisable, indent=2), encoding="utf-8")

    print(f"report  -> {args.out_md}")
    print(f"stats   -> {args.out_json}")
    for path in figures:
        print(f"figure  -> {path}")


if __name__ == "__main__":
    main()
