"""CLI: assemble the model comparison from finished runs.

Reads each run's metrics and evaluation files and renders one table, so the
comparison is built from what the runs actually recorded rather than from
numbers copied into a document by hand.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .labels import LABEL_NAMES


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("run_dirs", type=Path, nargs="+", help="training output directories")
    parser.add_argument("--split", default="test")
    parser.add_argument("--out", type=Path, default=Path("docs/results.md"))
    return parser.parse_args()


def load_run(run_dir: Path, split: str) -> dict | None:
    metrics_path = run_dir / "metrics.json"
    if not metrics_path.exists():
        print(f"skipping {run_dir}: no metrics.json")
        return None
    summary = json.loads(metrics_path.read_text(encoding="utf-8"))

    evaluation_path = run_dir / f"evaluation_{split}.json"
    evaluation = (
        json.loads(evaluation_path.read_text(encoding="utf-8"))
        if evaluation_path.exists()
        else None
    )
    return {"dir": run_dir, "summary": summary, "evaluation": evaluation}


def _row(values: list) -> str:
    return "| " + " | ".join(str(v) for v in values) + " |"


def render(runs: list[dict], split: str) -> str:
    lines = [
        "# Model comparison",
        "",
        f"Generated by `legal-risk-compare` from the runs themselves, on the {split} split.",
        "Every model saw identical chunks, identical document-level splits, the same",
        "weighted loss and the same per-label threshold tuning, so the differences below",
        "are differences between models.",
        "",
        "## Chunk-level results",
        "",
        _row(["Model", "Context", "Chunk words", "macro F1", "macro AP", "Best epoch"]),
        _row(["---", "---:", "---:", "---:", "---:", "---:"]),
    ]
    for run in runs:
        summary = run["summary"]
        tuned = summary.get("test_at_tuned_thresholds", {})
        chunking = summary.get("chunking", {})
        lines.append(
            _row(
                [
                    summary.get("checkpoint", summary["model"]),
                    chunking.get("max_length", "—"),
                    chunking.get("window", "—"),
                    f"{tuned.get('macro_f1', float('nan')):.3f}",
                    f"{tuned.get('macro_average_precision') or float('nan'):.3f}",
                    summary.get("best_epoch", "—"),
                ]
            )
        )

    lines += ["", "## Per-class F1", "", _row(["Model"] + list(LABEL_NAMES)), _row(["---"] + ["---:"] * len(LABEL_NAMES))]
    for run in runs:
        tuned = run["summary"].get("test_at_tuned_thresholds", {})
        per_class = {row["label"]: row["f1"] for row in tuned.get("per_class", [])}
        lines.append(
            _row([run["summary"]["model"]] + [f"{per_class.get(name, float('nan')):.3f}" for name in LABEL_NAMES])
        )

    documented = [run for run in runs if run["evaluation"]]
    if documented:
        lines += [
            "",
            "## Document-level results",
            "",
            "Chunk predictions pooled to a contract-level decision. This is the number that",
            "matters for the tool as it would be used: does this contract contain the clause?",
            "",
            _row(["Model", "Pooling", "macro F1", "macro AP"]),
            _row(["---", "---", "---:", "---:"]),
        ]
        for run in documented:
            evaluation = run["evaluation"]
            document = evaluation["document_level"]
            lines.append(
                _row(
                    [
                        run["summary"]["model"],
                        evaluation["pooling"],
                        f"{document['macro_f1']:.3f}",
                        f"{document['macro_average_precision'] or float('nan'):.3f}",
                    ]
                )
            )

    lines += [
        "",
        "## Reading this table",
        "",
        "**Problem 1** is the BERT against Legal-BERT row pair. They differ only in",
        "pretraining corpus, so the gap between them is the value of domain adaptation.",
        "Look at the per-class columns rather than the macro score: the hypothesis is that",
        "the gain concentrates in labels carried by legal vocabulary and is smallest for",
        "labels carried by ordinary English.",
        "",
        "**Problem 2** is BERT against Longformer. Both are trained on chunks, because 70%",
        "of contracts exceed 4,096 tokens as well; what differs is how much context one",
        "chunk holds. The comparison measures whether more surrounding contract makes a",
        "clause easier to recognise.",
        "",
        "**The CNN row is the floor.** A pretrained model that does not clear it by a",
        "useful margin is not earning its parameters, and the per-class columns say",
        "where any margin actually comes from.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    runs = [run for run in (load_run(d, args.split) for d in args.run_dirs) if run]
    if not runs:
        raise SystemExit("no runs with metrics.json found")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(runs, args.split), encoding="utf-8")
    print(f"compared {len(runs)} runs -> {args.out}")


if __name__ == "__main__":
    main()
